[package]
name = "programming"
version = "1.0.0"
authors = ["Christian D. Valenti <christian.valenti97@gmail.com"]
edition = "2021"

[[bin]]
name = "main"
path = "leetcode/0345_reverse_vowels_of_string.rs"
