[package]
name = "programming"
version = "1.0.0"
authors = ["Christian D. Valenti <christian.valenti97@gmail.com"]
edition = "2021"

[[bin]]
name = "main"
path = "leetcode/0088_merge_sorted_array.rs"
